# Generated by Django 3.1.7 on 2021-08-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animelist',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
